export const RegistrationError = 'Что-то пошло не так...';
export const RegistrationErrorFields = 'Неправильная почта или пароль.';
export const LoginFieldsError = 'Не заполнено одно из полей.';
export const LoginEmailError = 'Пользователь с указанным email не найден.';
export const TryAgainError = 'Что-то пошло не так. Попробуйте еще раз.';
export const ProfileError = 'Произошла ошибка при получении данных.';
export const ProfileUpdateSuccess = 'Данные профиля успешно обновлены.';
export const ProfileUpdateError = 'Ошибка при обновлении данных профиля.';
export const SearchErrorAdvice = 'Во время запроса произошла ошибка. Возможно, проблема с соединением или сервер недоступен. Подождите немного и попробуйте ещё раз.';